/* shrink table */
/* http://www.dba-oracle.com/t_alter_table_shrink_space_command.htm */
ALTER TABLE SCHEMA_NAME.TABLE_NAME ENABLE ROW MOVEMENT;
ALTER TABLE SCHEMA_NAME.TABLE_NAME SHRINK SPACE COMPACT;
ALTER TABLE SCHEMA_NAME.TABLE_NAME DISABLE ROW MOVEMENT;