/* show table info */
SELECT COLUMN_NAME,
  DATA_TYPE,
  DATA_LENGTH,
  NULLABLE,
  COLUMN_ID POS
FROM SYS.DBA_TAB_COLUMNS
WHERE OWNER    = :OWNER
AND TABLE_NAME = :TABLE_NAME
ORDER BY COLUMN_ID;

/* table size info */
SELECT PCT_FREE,
  PCT_INCREASE,
  INITIAL_EXTENT,
  NEXT_EXTENT,
  MAX_EXTENTS,
  NUM_ROWS,
  AVG_ROW_LEN
FROM SYS.DBA_TABLES
WHERE OWNER    = :OWNER
AND TABLE_NAME = :TABLE_NAME;
