/* slow sql report */
SELECT *
FROM
  (SELECT B.USERNAME ,
    NVL(A.OPTIMIZER_COST,0) COST_SQL,
    A.EXECUTIONS,
    TRUNC((A.ELAPSED_TIME /1000),0) TIMP_SEC,
    TRUNC((A.ELAPSED_TIME /(1000*60)),0) TIMP_MIN,
    TRUNC(A.ELAPSED_TIME  /(1000*(A.EXECUTIONS+1)),0) AVG_TIME,
    A.SQL_FULLTEXT,
    /*A.SQL_TEXT,*/
    A.SQL_ID,
    A.CHILD_NUMBER,
    A.DISK_READS,
    A.FIRST_LOAD_TIME,
    A.LAST_LOAD_TIME
  FROM V$SQL A,
    DBA_USERS B
  WHERE A.PARSING_USER_ID = B.USER_ID
    /*AND B.USERNAME ='SCHEMA'*/
    /*A.LAST_LOAD_TIME SEE https://docs.oracle.com/cd/b19306_01/server.102/b14237/dynviews_2113.htm#refrn30246 */
  AND A.LAST_LOAD_TIME BETWEEN '2018-04-20/00:00:00' AND '2019-04-25/00:00:00'
    /*ONLY JAVA*/
  AND UPPER(MODULE) LIKE 'JDBC%'
    /*EXCEPTION */
  AND B.USERNAME NOT IN ('SYS', 'SYSTEM', 'RMAN','SYSMAN')
  AND UPPER(A.SQL_TEXT) NOT LIKE UPPER('SELECT 1 FROM DUAL%')
  AND UPPER(A.SQL_TEXT) NOT LIKE UPPER('SELECT TRIGGER_NAME, TRIGGER_GROUP%')
  AND UPPER(A.SQL_TEXT) NOT LIKE UPPER('BEGIN %')
  AND UPPER(A.SQL_TEXT) NOT LIKE UPPER('%QRTZ_%')
  ORDER BY COST_SQL DESC ,
    ELAPSED_TIME DESC
  )
WHERE ROWNUM < 100 ;
